### ISSUE TITLE
部分 JS 没有被缓存到

### ISSUE THREAD

**Issue by kamingchan** [MoeNetwork/MoeCDN-WordPress#1]
https://gravatar-ssl.moefont.com/js/gprofiles.js?ver=2016Janaa 

这个资源 404 了，可是源站是能访问的，麻烦修复一下。

btw，很感谢你们的 CDN 服务。

**Comment by cuteSakuraHime** [comment]
这个是我们没有做反代的缘故，我们只反代了/Avatar，建议这个js放在你的本地或者使用Gravatar的源

**Comment by kamingchan** [comment]
然而你们的插件是把链接给替换了。
就是说，如果我这个 JS 要用别的 CDN，就只能放弃你们插件了？

**Comment by cuteSakuraHime** [comment]
请提供一下详细的站点url，可能是我们插件的问题导致替换了这个链接，我们会改进，谢谢您。

**Comment by kamingchan** [comment]
[t.32ph.com](t.32ph.com) thx

**Comment by cuteSakuraHime** [comment]
引入了`gprofiles.js`后发现还有

`services.css hovercard.css` 现在 一并引入了

**Comment by kamingchan** [comment]
好的 :)
